apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jenkins-web
  annotations:
spec:
  ingressClassName: nginx
  rules:
 # - host: 
  - http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: jenkins-ui
            port:
              number: 8080
