apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-account
  namespace: jenkins
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::445425982647:role/eks-jenkins-us-west-tf20220119122933960400000002
